name: Release
on:
  push:
    branches:
      - 813/circle-ci-github-actions

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # https://github.com/actions/checkout

      - name: Setup Node.js
        uses: actions/setup-node@v1 # https://github.com/actions/setup-node
        with:
          node-version: 12

      - name: Install
        run: yarn --offline --frozen-lockfile

      - name: Build
        run: scripts/ci/build.sh

      - name: Test
        run: yarn test

      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
